# Dockerfile for Python based RDKit implementation
# Based on Centos7

FROM centos:7
LABEL maintainer="Tim Dudgeon<tdudgeon@informaticsmatters.com>"

RUN yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

RUN yum update -y &&\
 yum install -y\
 python\
 python-devel\
 numpy\
 python2-pip\
 boost &&\
 boost-python &&\
 yum clean -y all &&\
 rm -rf /var/cache/yum

ARG TAG=latest

COPY artifacts/$TAG/rpms/*.rpm /tmp/
RUN rpm -iv /tmp/*.rpm && rm -f /tmp/*.rpm
WORKDIR /

# add the rdkit user
RUN useradd -u 1000 -U -G 0 rdkit
USER 1000
