# Dockerfile for Java based RDKit implementation
# Based on Debian.

FROM debian:bookworm
LABEL maintainer="Tim Dudgeon<tdudgeon@informaticsmatters.com>"

ARG TARGETARCH
ARG BOOST_VER=1.81.0

RUN apt-get update &&\
 apt-get upgrade -y &&\
 apt-get install -y --no-install-recommends\
 openjdk-17-jre-headless\
 libboost-system$BOOST_VER\
 libboost-thread$BOOST_VER\
 libboost-serialization$BOOST_VER\
 libboost-regex$BOOST_VER\
 libboost-chrono$BOOST_VER\
 libboost-date-time$BOOST_VER\
 libboost-atomic$BOOST_VER\
 libboost-iostreams$BOOST_VER\
 libfreetype6 &&\
 apt-get clean -y

ARG DOCKER_TAG=latest

COPY artifacts/debian/$DOCKER_TAG/java/* /rdkit/gmwrapper/
COPY artifacts/debian/$DOCKER_TAG/debs/RDKit-*-Linux-Runtime.deb /tmp/
RUN dpkg -i /tmp/*.deb && rm -f /tmp/*.deb
WORKDIR /

ENV JAVA_HOME /usr/lib/jvm/java-17-openjdk-${TARGETARCH}
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/rdkit/gmwrapper
ENV CLASSPATH=/rdkit/gmwrapper/org.RDKit.jar
ENV RDBASE=/usr/share/RDKit

# add the rdkit user
RUN useradd -u 1000 -U -G 0 -m rdkit
USER 1000
