# Dockerfile for Java based RDKit implementation
# Based on Debian.

FROM informaticsmatters/tomcat:8.5-jre11
LABEL maintainer="Tim Dudgeon<tdudgeon@informaticsmatters.com>"

USER root

RUN apt-get update &&\
 apt-get upgrade -y &&\ 
 apt-get install -y --no-install-recommends\
 unzip\
 libboost-system1.74.0\
 libboost-thread1.74.0\
 libboost-serialization1.74.0\
 libboost-regex1.74.0\
 libboost-chrono1.74.0\
 libboost-date-time1.74.0\
 libboost-atomic1.74.0\
 libboost-iostreams1.74.0\
 libfreetype6-dev &&\
 apt-get clean -y

ARG DOCKER_TAG=latest

COPY artifacts/debian/$DOCKER_TAG/java/* /rdkit/gmwrapper/
COPY artifacts/debian/$DOCKER_TAG/debs/RDKit-*-Linux-Runtime.deb /tmp/
RUN dpkg -i /tmp/*.deb && rm -f /tmp/*.deb

USER 501

WORKDIR $CATALINA_HOME
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/rdkit/gmwrapper
ENV CLASSPATH=/rdkit/gmwrapper/org.RDKit.jar
ENV RDBASE=/usr/share/RDKit/

RUN echo "CLASSPATH=/rdkit/gmwrapper/org.RDKit.jar\n" > /usr/local/tomcat/bin/setenv.sh

