# Dockerfile for building RDKit artifacts.
# This is a heavyweight image containing all aspects of RDKit plus the build system.
# It's purpose is to create the RDKit artifacts that will be deployed to lighter weigth images.


FROM fedora:30
LABEL maintainer="Tim Dudgeon<tdudgeon@informaticsmatters.com>"


RUN dnf update -y &&\
  dnf groupinstall -y "Development Tools" &&\
  dnf install -y --setopt=override_install_langs=en_US.utf8 --setopt=tsflags=nodocs\
  cmake\
  tk-devel\
  readline-devel\
  zlib-devel\
  bzip2-devel\
  sqlite-devel\
  python3-devel\
  numpy\
  boost\
  boost-devel\
  boost-python3-devel\
  g++\
  eigen3\
  eigen3-devel\
  swig\
  git\
  java-1.8.0-openjdk-devel &&\
#  java-11-openjdk-devel &&\
  dnf clean all &&\
  rm -rf /var/cache/dnf

ARG RDKIT_BRANCH=master
WORKDIR /
RUN git clone -b $RDKIT_BRANCH --single-branch https://github.com/rdkit/rdkit.git

ENV RDBASE=/rdkit
ENV JAVA_HOME=/usr/lib/jvm/jre

RUN mkdir $RDBASE/build
WORKDIR $RDBASE/build

RUN cmake -Wno-dev\
  -DRDK_INSTALL_INTREE=OFF\
  -DRDK_BUILD_INCHI_SUPPORT=OFF\
  -DRDK_BUILD_AVALON_SUPPORT=ON\
  -DRDK_BUILD_PYTHON_WRAPPERS=ON\
  -DPYTHON_EXECUTABLE=/usr/bin/python3\
  -DRDK_BUILD_SWIG_WRAPPERS=ON\
  -DCMAKE_INSTALL_PREFIX=/usr\
  ..

RUN nproc=$(getconf _NPROCESSORS_ONLN)\
  && make -j $(( nproc > 2 ? nproc - 2 : 1 ))\
  && make install

ENV CLASSPATH=$RDBASE/Code/JavaWrappers/gmwrapper/org.RDKit.jar
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$RDBASE/lib:$RDBASE/Code/JavaWrappers/gmwrapper:/usr/lib/x86_64-linux-gnu
ENV PYTHONPATH=$PYTHONPATH:$RDBASE
WORKDIR $RDBASE

