# Dockerfile for Java based RDKit implementation
# Based on Debian.

FROM debian:bullseye
LABEL maintainer="Tim Dudgeon<tdudgeon@informaticsmatters.com>"


RUN apt-get update &&\
 apt-get upgrade -y &&\
 apt-get install -y --no-install-recommends\
 openjdk-11-jre-headless\
 libboost-system1.74.0\
 libboost-thread1.74.0\
 libboost-serialization1.74.0\
 libboost-regex1.74.0\
 libboost-chrono1.74.0\
 libboost-date-time1.74.0\
 libboost-atomic1.74.0\
 libboost-iostreams1.74.0\
 libfreetype6 &&\
 apt-get clean -y

ARG DOCKER_TAG=latest

COPY artifacts/debian/$DOCKER_TAG/java/* /rdkit/gmwrapper/
COPY artifacts/debian/$DOCKER_TAG/debs/RDKit-*-Linux-Runtime.deb /tmp/
RUN dpkg -i /tmp/*.deb && rm -f /tmp/*.deb
WORKDIR / 

ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/rdkit/gmwrapper
ENV CLASSPATH=/rdkit/gmwrapper/org.RDKit.jar
ENV RDBASE=/usr/share/RDKit

# add the rdkit user
RUN useradd -u 1000 -U -G 0 -m rdkit
USER 1000
