# Dockerfile for Python3 based RDKit implementation
# Based on Debian. Does not include Python2.

FROM debian:bullseye
LABEL maintainer="Tim Dudgeon<tdudgeon@informaticsmatters.com>"

ARG BOOST_VERSION=1.74

RUN apt-get update -y &&\ 
 apt-get upgrade -y &&\
 apt-get install -y --no-install-recommends\
 python3\
 python3-dev\
 python3-numpy\
 python3-pip\
 python3-setuptools\
 python3-wheel\
 python3-six\
 gcc\
 libboost-system${BOOST_VERSION}\
 libboost-thread${BOOST_VERSION}\
 libboost-serialization${BOOST_VERSION}\
 libboost-python${BOOST_VERSION}\
 libboost-regex${BOOST_VERSION}\
 libboost-chrono${BOOST_VERSION}\
 libboost-date-time${BOOST_VERSION}\
 libboost-atomic${BOOST_VERSION}\
 libboost-iostreams${BOOST_VERSION}\
 sqlite3\
 wget\
 zip\
 libfreetype6 &&\
 apt-get clean -y

ARG DOCKER_TAG=latest

COPY artifacts/debian/$DOCKER_TAG/debs/RDKit-*-Linux-Runtime.deb artifacts/debian/$DOCKER_TAG/debs/RDKit-*-Linux-Python.deb /tmp/
RUN dpkg -i /tmp/*.deb && rm -f /tmp/*.deb

# symlink python3 to python
RUN cd /usr/bin && ln -s python3 python

ENV RDBASE=/usr/share/RDKit

WORKDIR /

# add the rdkit user
RUN useradd -u 1000 -g 0 -m rdkit
USER 1000
