# Dockerfile for Python3 based RDKit implementation
# Based on Debian.

FROM debian:bullseye
LABEL maintainer="Tim Dudgeon<tdudgeon@informaticsmatters.com>"

ARG BOOST_VER=1.74.0

RUN apt-get update &&\
 apt-get upgrade -y &&\ 
 apt-get install -y --no-install-recommends\
 python3\
 python3-dev\
 python3-numpy\
 python3-pip\
 python3-setuptools\
 python3-wheel\
 python3-six\
 python-is-python3\
 gcc\
 libboost-system$BOOST_VER\
 libboost-thread$BOOST_VER\
 libboost-serialization$BOOST_VER\
 libboost-python$BOOST_VER\
 libboost-regex$BOOST_VER\
 libboost-chrono$BOOST_VER\
 libboost-date-time$BOOST_VER\
 libboost-atomic$BOOST_VER\
 libboost-iostreams$BOOST_VER\
 sqlite3\
 wget\
 zip\
 libfreetype6 &&\
 apt-get clean -y

ARG DOCKER_TAG=latest

COPY artifacts/debian/$DOCKER_TAG/debs/RDKit-*-Linux-Runtime.deb artifacts/debian/$DOCKER_TAG/debs/RDKit-*-Linux-Python.deb /tmp/
RUN dpkg -i /tmp/*.deb && rm -f /tmp/*.deb

ENV RDBASE=/usr/share/RDKit

WORKDIR /

# add the rdkit user
RUN useradd -u 1000 -g 0 -m rdkit
USER 1000
