# Dockerfile for Python3 based RDKit implementation
# Based on Centos8
# See comments in build-centos.sh for details.

FROM centos:8
LABEL maintainer="Tim Dudgeon<tdudgeon@informaticsmatters.com>"

RUN yum update -y &&\
 sed -i 's/enabled=0/enabled=1/' /etc/yum.repos.d/CentOS-Linux-PowerTools.repo &&\
 yum install -y --setopt=tsflags=nodocs --setopt=override_install_langs=en_US.utf8\
 python3\
 python3-devel\
 python3-numpy\
 python3-pip\
 python3-setuptools\
 python3-six\
 boost-system\
 boost-thread\
 boost-serialization\
 boost-regex\
 boost-chrono\
 boost-date-time\
 boost-atomic\
 boost-iostreams\
 boost-python3\
 freetype\
 procps-ng &&\
 yum clean -y all &&\
 rm -rf /var/cache/yum

ARG DOCKER_TAG=latest

COPY artifacts/centos/$DOCKER_TAG/rpms/RDKit-*-Linux-Runtime.rpm artifacts/centos/$DOCKER_TAG/rpms/RDKit-*-Linux-Python.rpm /tmp/
RUN rpm --nodeps -iv /tmp/*.rpm && rm -f /tmp/*.rpm

ENV RDBASE=/usr/share/RDKit

WORKDIR /

# add the rdkit user
RUN useradd -u 1000 -U -G 0 rdkit
USER 1000
