FROM centos/postgresql-96-centos7
LABEL maintainer="Tim Dudgeon<tdudgeon@informaticsmatters.com>"

USER root

RUN yum install -y --setopt=tsflags=nodocs --setopt=override_install_langs=en_US.utf8\
 rh-postgresql96-postgresql-devel\
 boost\
 cairo &&\
 yum clean -y all &&\
 rm -rf /var/cache/yum

USER 26
